ALTER TYPE "MissionStatus" ADD VALUE IF NOT EXISTS 'UNDER_REVIEW';
ALTER TYPE "MissionStatus" ADD VALUE IF NOT EXISTS 'REMOVED';

ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'DISQUALIFIED';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'PAID';

CREATE TYPE "PayoutStatus" AS ENUM ('UNPAID', 'PAID', 'FAILED');
CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'SUSPENDED');

ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'SUBMISSION_DISQUALIFIED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'SUBMISSION_PAID';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'USER_SUSPENDED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'USER_UNSUSPENDED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'ADMIN_NOTE_ADDED';

ALTER TABLE "users" ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE "submissions" ADD COLUMN "adminNote" TEXT;
ALTER TABLE "submissions" ADD COLUMN "payoutAmount" DECIMAL(12,2);
ALTER TABLE "submissions" ADD COLUMN "payoutWallet" TEXT;
ALTER TABLE "submissions" ADD COLUMN "payoutTxHash" TEXT;
ALTER TABLE "submissions" ADD COLUMN "payoutStatus" "PayoutStatus" NOT NULL DEFAULT 'UNPAID';
ALTER TABLE "submissions" ADD COLUMN "payoutNote" TEXT;
ALTER TABLE "submissions" ADD COLUMN "paidAt" TIMESTAMP(3);

CREATE TABLE "admin_notes" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "adminUserId" TEXT,
  "note" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "admin_notes_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "admin_notes" ADD CONSTRAINT "admin_notes_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "admin_notes" ADD CONSTRAINT "admin_notes_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
